// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OutboxesColumns holds the columns for the "outboxes" table.
	OutboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "topic", Type: field.TypeString},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OutboxesTable holds the schema information for the "outboxes" table.
	OutboxesTable = &schema.Table{
		Name:       "outboxes",
		Columns:    OutboxesColumns,
		PrimaryKey: []*schema.Column{OutboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outbox_created_at_topic",
				Unique:  false,
				Columns: []*schema.Column{OutboxesColumns[4], OutboxesColumns[1]},
			},
		},
	}
	// ProcessedMessagesColumns holds the columns for the "processed_messages" table.
	ProcessedMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "message_id", Type: field.TypeUUID},
		{Name: "message_topic", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProcessedMessagesTable holds the schema information for the "processed_messages" table.
	ProcessedMessagesTable = &schema.Table{
		Name:       "processed_messages",
		Columns:    ProcessedMessagesColumns,
		PrimaryKey: []*schema.Column{ProcessedMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "processedmessage_message_id_message_topic",
				Unique:  true,
				Columns: []*schema.Column{ProcessedMessagesColumns[1], ProcessedMessagesColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OutboxesTable,
		ProcessedMessagesTable,
		UsersTable,
	}
)

func init() {
}
