// Code generated by ent, DO NOT EDIT.

package ent

import (
	"database/sql"
	"fmt"
)

func (c *Client) DB() (*sql.DB, error) {
	driverDB, ok := c.driver.(interface {
		DB() *sql.DB
	})
	if !ok {
		return nil, fmt.Errorf("Driver.DB is not supported")
	}
	return driverDB.DB(), nil
}
