// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/igmagollo/undine/example/ent/predicate"
	"github.com/igmagollo/undine/example/ent/processedmessage"
)

// ProcessedMessageDelete is the builder for deleting a ProcessedMessage entity.
type ProcessedMessageDelete struct {
	config
	hooks    []Hook
	mutation *ProcessedMessageMutation
}

// Where appends a list predicates to the ProcessedMessageDelete builder.
func (pmd *ProcessedMessageDelete) Where(ps ...predicate.ProcessedMessage) *ProcessedMessageDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *ProcessedMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pmd.sqlExec, pmd.mutation, pmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *ProcessedMessageDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *ProcessedMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(processedmessage.Table, sqlgraph.NewFieldSpec(processedmessage.FieldID, field.TypeUUID))
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pmd.mutation.done = true
	return affected, err
}

// ProcessedMessageDeleteOne is the builder for deleting a single ProcessedMessage entity.
type ProcessedMessageDeleteOne struct {
	pmd *ProcessedMessageDelete
}

// Where appends a list predicates to the ProcessedMessageDelete builder.
func (pmdo *ProcessedMessageDeleteOne) Where(ps ...predicate.ProcessedMessage) *ProcessedMessageDeleteOne {
	pmdo.pmd.mutation.Where(ps...)
	return pmdo
}

// Exec executes the deletion query.
func (pmdo *ProcessedMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{processedmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *ProcessedMessageDeleteOne) ExecX(ctx context.Context) {
	if err := pmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
