// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/igmagollo/undine/example/ent/predicate"
	"github.com/igmagollo/undine/example/ent/processedmessage"
)

// ProcessedMessageQuery is the builder for querying ProcessedMessage entities.
type ProcessedMessageQuery struct {
	config
	ctx        *QueryContext
	order      []processedmessage.OrderOption
	inters     []Interceptor
	predicates []predicate.ProcessedMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProcessedMessageQuery builder.
func (pmq *ProcessedMessageQuery) Where(ps ...predicate.ProcessedMessage) *ProcessedMessageQuery {
	pmq.predicates = append(pmq.predicates, ps...)
	return pmq
}

// Limit the number of records to be returned by this query.
func (pmq *ProcessedMessageQuery) Limit(limit int) *ProcessedMessageQuery {
	pmq.ctx.Limit = &limit
	return pmq
}

// Offset to start from.
func (pmq *ProcessedMessageQuery) Offset(offset int) *ProcessedMessageQuery {
	pmq.ctx.Offset = &offset
	return pmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pmq *ProcessedMessageQuery) Unique(unique bool) *ProcessedMessageQuery {
	pmq.ctx.Unique = &unique
	return pmq
}

// Order specifies how the records should be ordered.
func (pmq *ProcessedMessageQuery) Order(o ...processedmessage.OrderOption) *ProcessedMessageQuery {
	pmq.order = append(pmq.order, o...)
	return pmq
}

// First returns the first ProcessedMessage entity from the query.
// Returns a *NotFoundError when no ProcessedMessage was found.
func (pmq *ProcessedMessageQuery) First(ctx context.Context) (*ProcessedMessage, error) {
	nodes, err := pmq.Limit(1).All(setContextOp(ctx, pmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{processedmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) FirstX(ctx context.Context) *ProcessedMessage {
	node, err := pmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProcessedMessage ID from the query.
// Returns a *NotFoundError when no ProcessedMessage ID was found.
func (pmq *ProcessedMessageQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pmq.Limit(1).IDs(setContextOp(ctx, pmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{processedmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProcessedMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProcessedMessage entity is found.
// Returns a *NotFoundError when no ProcessedMessage entities are found.
func (pmq *ProcessedMessageQuery) Only(ctx context.Context) (*ProcessedMessage, error) {
	nodes, err := pmq.Limit(2).All(setContextOp(ctx, pmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{processedmessage.Label}
	default:
		return nil, &NotSingularError{processedmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) OnlyX(ctx context.Context) *ProcessedMessage {
	node, err := pmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProcessedMessage ID in the query.
// Returns a *NotSingularError when more than one ProcessedMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (pmq *ProcessedMessageQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pmq.Limit(2).IDs(setContextOp(ctx, pmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{processedmessage.Label}
	default:
		err = &NotSingularError{processedmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProcessedMessages.
func (pmq *ProcessedMessageQuery) All(ctx context.Context) ([]*ProcessedMessage, error) {
	ctx = setContextOp(ctx, pmq.ctx, "All")
	if err := pmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProcessedMessage, *ProcessedMessageQuery]()
	return withInterceptors[[]*ProcessedMessage](ctx, pmq, qr, pmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) AllX(ctx context.Context) []*ProcessedMessage {
	nodes, err := pmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProcessedMessage IDs.
func (pmq *ProcessedMessageQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pmq.ctx.Unique == nil && pmq.path != nil {
		pmq.Unique(true)
	}
	ctx = setContextOp(ctx, pmq.ctx, "IDs")
	if err = pmq.Select(processedmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pmq *ProcessedMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pmq.ctx, "Count")
	if err := pmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pmq, querierCount[*ProcessedMessageQuery](), pmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) CountX(ctx context.Context) int {
	count, err := pmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pmq *ProcessedMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pmq.ctx, "Exist")
	switch _, err := pmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pmq *ProcessedMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := pmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProcessedMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pmq *ProcessedMessageQuery) Clone() *ProcessedMessageQuery {
	if pmq == nil {
		return nil
	}
	return &ProcessedMessageQuery{
		config:     pmq.config,
		ctx:        pmq.ctx.Clone(),
		order:      append([]processedmessage.OrderOption{}, pmq.order...),
		inters:     append([]Interceptor{}, pmq.inters...),
		predicates: append([]predicate.ProcessedMessage{}, pmq.predicates...),
		// clone intermediate query.
		sql:  pmq.sql.Clone(),
		path: pmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MessageID uuid.UUID `json:"message_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProcessedMessage.Query().
//		GroupBy(processedmessage.FieldMessageID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pmq *ProcessedMessageQuery) GroupBy(field string, fields ...string) *ProcessedMessageGroupBy {
	pmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProcessedMessageGroupBy{build: pmq}
	grbuild.flds = &pmq.ctx.Fields
	grbuild.label = processedmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MessageID uuid.UUID `json:"message_id,omitempty"`
//	}
//
//	client.ProcessedMessage.Query().
//		Select(processedmessage.FieldMessageID).
//		Scan(ctx, &v)
func (pmq *ProcessedMessageQuery) Select(fields ...string) *ProcessedMessageSelect {
	pmq.ctx.Fields = append(pmq.ctx.Fields, fields...)
	sbuild := &ProcessedMessageSelect{ProcessedMessageQuery: pmq}
	sbuild.label = processedmessage.Label
	sbuild.flds, sbuild.scan = &pmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProcessedMessageSelect configured with the given aggregations.
func (pmq *ProcessedMessageQuery) Aggregate(fns ...AggregateFunc) *ProcessedMessageSelect {
	return pmq.Select().Aggregate(fns...)
}

func (pmq *ProcessedMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pmq); err != nil {
				return err
			}
		}
	}
	for _, f := range pmq.ctx.Fields {
		if !processedmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pmq.path != nil {
		prev, err := pmq.path(ctx)
		if err != nil {
			return err
		}
		pmq.sql = prev
	}
	return nil
}

func (pmq *ProcessedMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProcessedMessage, error) {
	var (
		nodes = []*ProcessedMessage{}
		_spec = pmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProcessedMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProcessedMessage{config: pmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pmq *ProcessedMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pmq.querySpec()
	_spec.Node.Columns = pmq.ctx.Fields
	if len(pmq.ctx.Fields) > 0 {
		_spec.Unique = pmq.ctx.Unique != nil && *pmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pmq.driver, _spec)
}

func (pmq *ProcessedMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(processedmessage.Table, processedmessage.Columns, sqlgraph.NewFieldSpec(processedmessage.FieldID, field.TypeUUID))
	_spec.From = pmq.sql
	if unique := pmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pmq.path != nil {
		_spec.Unique = true
	}
	if fields := pmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processedmessage.FieldID)
		for i := range fields {
			if fields[i] != processedmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pmq *ProcessedMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pmq.driver.Dialect())
	t1 := builder.Table(processedmessage.Table)
	columns := pmq.ctx.Fields
	if len(columns) == 0 {
		columns = processedmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pmq.sql != nil {
		selector = pmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pmq.ctx.Unique != nil && *pmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pmq.predicates {
		p(selector)
	}
	for _, p := range pmq.order {
		p(selector)
	}
	if offset := pmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProcessedMessageGroupBy is the group-by builder for ProcessedMessage entities.
type ProcessedMessageGroupBy struct {
	selector
	build *ProcessedMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pmgb *ProcessedMessageGroupBy) Aggregate(fns ...AggregateFunc) *ProcessedMessageGroupBy {
	pmgb.fns = append(pmgb.fns, fns...)
	return pmgb
}

// Scan applies the selector query and scans the result into the given value.
func (pmgb *ProcessedMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pmgb.build.ctx, "GroupBy")
	if err := pmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcessedMessageQuery, *ProcessedMessageGroupBy](ctx, pmgb.build, pmgb, pmgb.build.inters, v)
}

func (pmgb *ProcessedMessageGroupBy) sqlScan(ctx context.Context, root *ProcessedMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pmgb.fns))
	for _, fn := range pmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pmgb.flds)+len(pmgb.fns))
		for _, f := range *pmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProcessedMessageSelect is the builder for selecting fields of ProcessedMessage entities.
type ProcessedMessageSelect struct {
	*ProcessedMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pms *ProcessedMessageSelect) Aggregate(fns ...AggregateFunc) *ProcessedMessageSelect {
	pms.fns = append(pms.fns, fns...)
	return pms
}

// Scan applies the selector query and scans the result into the given value.
func (pms *ProcessedMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pms.ctx, "Select")
	if err := pms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcessedMessageQuery, *ProcessedMessageSelect](ctx, pms.ProcessedMessageQuery, pms, pms.inters, v)
}

func (pms *ProcessedMessageSelect) sqlScan(ctx context.Context, root *ProcessedMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pms.fns))
	for _, fn := range pms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
