// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
)

func (c *Client) WithTx(ctx context.Context, transactionalFn func(ctx context.Context) error) error {
	tx, err := c.Tx(ctx)
	if err != nil {
		return err
	}
	tctx := NewTxContext(ctx, tx)
	defer func() {
		if v := recover(); v != nil {
			tx.Rollback()
			panic(v)
		}
	}()
	if err := transactionalFn(tctx); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			err = fmt.Errorf("%w: rolling back transaction: %v", err, rerr)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("committing transaction: %w", err)
	}
	return nil
}
